
INSERT INTO users Values ('1', '織田信長', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0)
;
INSERT INTO users Values ('2', 'お市', '2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0)
;
INSERT INTO users Values ('3', '伊達政宗', '1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0)
;
